### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data//nipsA_offline_num/train_features.npy'

### ISSUE THREAD

**Issue by linxingliang** [motefly/DeepGBM#11]
I used your script to generate, and found that there are no files in the nipsa offline num folder, but there are files in other folders

**Comment by motefly** [comment]
Please check the log and arguments carefully, or you can paste the logs here for further discussion.

**Comment by linxingliang** [comment]
i have solve this issues, thx.
