### ISSUE TITLE
how to modify the network for multi-classification?

### ISSUE THREAD

**Issue by stevenzhang027** [motefly/DeepGBM#13]
I'm implementing a version for a multi-classification task, not sure where to change the work.
Is it right to change the **BatchDense** part with parameter **out_features** from "1" in original codes to n_classes in my case?

**Comment by motefly** [comment]
In fact, I haven't tried it for multi-classification, because there are #CLASS_NUM-x more trees in LGB for multi-classification, where each part of the trees only contributes to one specifical class. Welcome more explorations in this direction if interest, thank you.

**Comment by stevenzhang027** [comment]
send you a email, looking forward to discussion for more details about the direction.

**Comment by Yang-HangWA** [comment]
So any help for deepGBM on multi-classification task? @stevenzhang027 @motefly
