### ISSUE TITLE
Dataset About Flight

### ISSUE THREAD

**Issue by htw2012** [motefly/DeepGBM#16]
Hello, 

I have downloaded the flight from site `http://stat-computing.org/dataexpo/2009/the-data.html`.
I find that there are 29 fields in this dataset, but 12 fields are used in your paper. I don't know the specific field in your paper is used, could you tell me the detail about how to use this dataset?

Thanks.

**Comment by motefly** [comment]
Refer to https://github.com/motefly/DeepGBM/blob/master/experiments/preprocess/encoding_nume.py#L262

**Comment by htw2012** [comment]
Thanks.
