### ISSUE TITLE
It seems I cannot find the paper in the arxiv, is there any place to find a copy?

### ISSUE THREAD

**Issue by imsheridan** [motefly/DeepGBM#2]
Hey dear author
I wants to get a copy of the orignal paper of DeepGBM: A Deep Learning Framework Distilled by GBDT for Online Prediction Tasks, is there any place to get one?

**Comment by motefly** [comment]
Hi,
We didn't upload the paper to Arxiv, and I think the final version will appear at https://www.kdd.org/kdd2019/accepted-papers around August. Thanks for your interest.

**Comment by motefly** [comment]
If you need to get the manuscript in advance, please email me and I will send you one, but please DO NOT distribute it.
