### ISSUE TITLE
请问zillow的测试集是哪个呢?

### ISSUE THREAD

**Issue by hanfu** [motefly/DeepGBM#25]
请问zillow的测试集是哪个呢? y_test是哪个?

**Comment by motefly** [comment]
请参阅 https://www.kaggle.com/c/zillow-prize-1/data 及 https://github.com/motefly/DeepGBM/blob/master/preprocess/encoding_cate.py#L135

**Comment by hanfu** [comment]
感谢回复. 
kaggle上只有训练集. encoding的代码是指定标签的代码. 
你给的snippet是合并属性表和数据表.
所以可以理解为zillow只有训练集有样本和标签, 测试集需要从训练集里自己划分出来. 是这么操作么? 
再次感谢!

**Comment by motefly** [comment]
嗯，应该是的。

**Comment by hanfu** [comment]
谢谢! 请问数据集里有哪些是提供了完整的训练和测试的标签的呢?

**Comment by motefly** [comment]
这个不重要，测试集都可以从公布了完整数据集（很多比赛可能大多都是只公开了完整的训练集）的基础上切割。
