### ISSUE TITLE
Can someone show an example of how to use DeepGBM with pd

### ISSUE THREAD

**Issue by m416kar98k** [motefly/DeepGBM#32]
`RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`

**Comment by sakibsadmanshajib** [comment]
I can help if I can get a little more context.

**Comment by jaronn** [comment]
download the code which include the example发自我的华为手机-------- 原始邮件 --------发件人： m416kar98k ***@***.***>日期： 2022年2月23日周三 清晨5:54收件人： motefly/DeepGBM ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [motefly/DeepGBM] Can someone show an example of how to use DeepGBM with pd (#32)
Closed #32.

**Comment by 3hope9** [comment]
> I can help if I can get a little more context.

I meet the same problem,can you help me?

**Comment by 3hope9** [comment]
> `RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`

I meet the same error,what's the problem?
