### ISSUE TITLE
Where to find the demo data？

### ISSUE THREAD

**Issue by zhenweilin** [motefly/DeepGBM#35]
Hi,

I've been exploring your DeepGBM project and I'm particularly interested in the dataset referenced in pro_nips_A.py (e.g., AA/AA_train1.solution). It seems these files are not included in the repository. Could you please provide the necessary data files or guide me on how to obtain them?

Thank you for your assistance!

Best regards

**Comment by zhenweilin** [comment]
Sorry， I found it in url https://www.4paradigm.com/content/details_85_1868.html

**Comment by jaronn** [comment]
Nice~
















At 2024-06-14 12:33:19, "Lin Zhenwei" ***@***.***> wrote:

Sorry， I found it in url https://www.4paradigm.com/content/details_85_1868.html
