### ISSUE TITLE
How preprocessing and encoding "Zillow Dataset"?

### ISSUE THREAD

**Issue by wakamezake** [motefly/DeepGBM#8]
Try to work kaggle notebook but I got error `KeyError: 'yearbuilt_cate'`.
[Kaggle MyNotebook - deepgbm-experiments-zillow](https://www.kaggle.com/wakamezake/deepgbm-experiments-zillow)

**Comment by motefly** [comment]
For Zillow, I clone the column "yearbuilt" one more time to new "yearbuilt_cate", one for numerical feature using and the copy one for category feature using.
