### ISSUE TITLE
when I use flight dataset, I run the main.py and show follow error

### ISSUE THREAD

**Issue by fengweisi** [motefly/DeepGBM#9]
![image](https://user-images.githubusercontent.com/21092180/64491009-93043f80-d295-11e9-951f-d8f28e5a6934.png)

**Comment by motefly** [comment]
I didn't meet it, and could you please give more detail description about it?

**Comment by fengweisi** [comment]
> I didn't meet it, and could you please give more detail description about it?

thank you answer,I fix it yesterday.Cause this error,because Torchvision's version is not working.when I install 0.2.0,the program can run.
